# Generated by Django 4.2.6 on 2023-10-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('rating_score', models.CharField(max_length=50)),
                ('answered_questions', models.CharField(max_length=50)),
                ('favorite', models.CharField(blank=True, max_length=50, null=True)),
                ('feature_0', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_1', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_5', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_6', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_7', models.CharField(blank=True, max_length=255, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_view', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_viewing', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
